fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_ADMIN)%'
        sender_name: '%env(MAILER_ADMIN)%'
    registration:
        confirmation:
            enabled: true
