knp_snappy:
    pdf:
        enabled: true
        binary:  "%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64"
        #binary:  /usr/bin/wkhtmltopdf
        options:
            - { name: 'page-size', value: 'A4' }
