vich_uploader:
    db_driver: orm
    twig: true
    mappings:
        structure_logo:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        receipt_sign:
            uri_prefix:         /uploads/signs
            upload_destination: '%kernel.project_dir%/public/uploads/signs'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
