vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        structure_logo:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
        receipt_sign:
            uri_prefix:         /uploads/signs
            upload_destination: '%kernel.project_dir%/public/uploads/signs'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            #namer:              vich_uploader.namer_origname
