# src/Pigass/CoreBundle/Resources/config/services.yml
services:
  pigass_core.menu_builder:
    class: Pigass\CoreBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

  pigass_core.menu.main:
    class: Knp\Menu\MenuItem
    factory: ["@pigass_core.menu_builder", createMainMenu]
    arguments: ["@request_stack","@security.authorization_checker"]
    tags:
      - { name: knp_menu.menu, alias: main }
