imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr_FR
    logo_dir: '%kernel.root_dir%/../web/uploads/'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 3600
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: { fallbacks: ["%locale%"]  }
    default_locale:  "%locale%"


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'PigassCoreBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: %kernel.debug%
    bundles:        [MopaBootstrapBundle, PigassCoreBundle]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~

# User control configuration
fos_user:
  db_driver:     orm
  firewall_name: main
  user_class:    Pigass\UserBundle\Entity\User
  from_email:
    address:     %mailer_mail%
    sender_name: Administrateur
  registration:
      confirmation:
          enabled: true

# Application's parameters configuration
kdb_parameters:
  db_driver: orm
  class:     Pigass\ParameterBundle\Entity\Parameter

# Pagination configuration
knp_paginator:
  page_range: 5                       # default page range used in pagination control
  default_options:
    page_name:           page         # page query parameter name
    sort_field_name:     sort         # sort field query parameter name
    sort_direction_name: direction    # sort direction query parameter name
    distinct:            true         # ensure distinct results, useful when ORM queries are using GROUP BY statements
    filter_field_name:   filterField
    filter_value_name:   filterValue
  template:
    pagination: MopaBootstrapBundle:Pagination:sliding.html.twig       # sliding pagination controls template
    filtration: KnpPaginatorBundle:Pagination:filtration.html.twig
    sortable:   KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

mopa_bootstrap:
    form: 
        show_legend: false
        show_child_legend: false
        render_required_asterisk: true
        render_optional_text: false
        checkbox_label: 'widget'
        error_type: 'block'
        collection:
            widget_remove_btn:
                icon: trash
                icon_inverted: true
            widget_add_btn:
                icon: plus-sign
    menu: ~
    navbar: ~
    initializr: 
        meta: 
            keywords: "choix de stage, simulation, interne, internat, évalutations de stage"
            author_name: "Pierre-François Angrand"
            nofollow: false
            noindex: false

payum:
    storages:
        Pigass\UserBundle\Entity\Payment: { doctrine: orm }
    security:
        token_storage:
            Pigass\UserBundle\Entity\PaymentToken: { doctrine: orm }
    dynamic_gateways:
        sonata_admin: false
        config_storage:
            Pigass\UserBundle\Entity\Gateway: { doctrine: orm }

jms_security_extra:
    secure_all_services: true
    enable_iddqd_attribute: false
    expressions: true

knp_snappy:
    pdf:
        enabled: true
        binary:  %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        #binary:  /usr/bin/wkhtmltopdf
        options:
            - { name: 'page-size', value: 'A4' }

vich_uploader:
    db_driver: orm
    mappings:
        structure_logo:
            uri_prefix: /images/logos
            upload_destination: '%kernel.root_dir%/../web/uploads/logos'
        receipt_sign:
            uri_prefix:         /uploads/signs
            upload_destination: '%kernel.root_dir%/../web/uploads/signs'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            #namer:              vich_uploader.namer_origname
