PigassRegister:
    resource: "@PigassCoreBundle/Controller/"
    type:     annotation

PigassParameter:
    resource: "@PigassParameterBundle/Controller/"
    type:     annotation

PigassUser:
  resource: "@PigassUserBundle/Controller/"
  type:     annotation

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /reset

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /user

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /fos

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    prefix: /user

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    prefix: /user
