security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_STRUCTURE: [ROLE_MEMBER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:         ^/
            form_login:
                provider:      fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
            logout:          true
            anonymous:       true
            remember_me:
                secret:      "%secret%"
                lifetime:    1296000
                path:        /
                domain:      ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fieldset/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ROLE_ADMIN] }
        - { path: ^/user/, roles: [ROLE_STUDENT, ROLE_ADMIN] }
